apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: backup
  name: backup
spec:
  replicas: 1
  selector:
    name: backup
  template:
    metadata:
      labels:
        name: backup
    spec:
      serviceAccountName: backup
      restartPolicy: Never
      containers:
      - command:
          - '/bin/sh'
          - '-c'
        args:
          - "source ./backup.sh"
        workingDir: /mnt/scripts
        image: registry.ocp4.example.com:8443/openshift4/ose-cli:v4.10
        imagePullPolicy: Always
        name: shell
        volumeMounts:
        - mountPath: /mnt/scripts
          name: scripts
        - mountPath: /mnt/backup
          name: backup-data
      volumes:
      - name: backup-data
        persistentVolumeClaim:
          claimName: data-postgresql-backup
      - name: scripts
        configMap:
          name: backup-scripts
