apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: pools-maintenance
spec:
  replicas: 15
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: registry.ocp4.example.com:8443/redhattraining/hello-world-nginx:v1.0
          name: hello-world
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: pools-maintenance
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-world
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: pools-maintenance
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: hello-world
---