apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: example
spec:
  storageClassDevices:
  - devicePaths:
    - /dev/disk/by-id/ata-crucial
    fsType: ext4
    storageClassName: foobar
    volumeMode: Filesystem
