apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: restore-controller
  name: restore-controller
spec:
  replicas: 1
  selector:
    name: restore-controller
  template:
    metadata:
      labels:
        name: restore-controller
    spec:
      serviceAccountName: backup
      restartPolicy: Never
      containers:
      - command:
          - "/bin/sh"
          - "-c"
          #- "tail"
          #- "-f"
        args:
          - "source ./restore-controller.sh"
          #- "/dev/null"
        workingDir: /mnt/scripts
        image: registry.ocp4.example.com:8443/openshift4/ose-cli:v4.10
        imagePullPolicy: Always
        name: shell
        volumeMounts:
        - mountPath: /mnt/scripts
          name: scripts
      volumes:
      - name: scripts
        configMap:
          name: restore-scripts

