apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: master
          image: registry.ocp4.example.com:8443/redhattraining/redis:6.2
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: ephemeral-backup
              mountPath: /data
      volumes:
        - name: ephemeral-backup
          emptyDir: {}

